### PR TITLE
fix(cmake): fix Mac error 'undefined symbols for architecture'

### LINKED ISSUE #5: Clang build issue: Undefined symbols for architecture x86_64 _IOPSGetTimeRemainingEstimate
Sorry for spamming issues, but after solving the first two issues and adding openssl include dir to INTERFACE_INCLUDE_DIRECTORIES I get the following:

```
[ 84%] Linking CXX executable monero-lws-admin
Undefined symbols for architecture x86_64:
  "_IOPSGetTimeRemainingEstimate", referenced from:
      cryptonote::miner::background_worker_thread() in libcryptonote_basic.a(miner.cpp.o)
      cryptonote::miner::on_battery_power() in libcryptonote_basic.a(miner.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/monero-lws-admin] Error 1
make[1]: *** [src/CMakeFiles/monero-lws-admin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

### PR DESCRIPTION
**Pull request by LeoNero**
Closes #5

I don't know if this is the best way to solve it. Any better idea is appreciated.

### CODE REVIEW

**Comment by selsta** [comment]
Can you test if

```
if(APPLE)
  find_library(IOKIT_LIBRARY IOKit)
  list(APPEND IMPORTED_MONERO_LIBRARIES IOKIT_LIBRARY)
endif()
```

works?

**Comment by LeoNero** [comment]
@selsta sorry for the delay, I was fixing an OpenSSL error lol

The option with `list(APPEND IMPORTED_MONERO_LIBRARIES ${IOKIT_LIBRARY})` works

**Comment by selsta** [comment]
Ok, can you update the PR? Using find_library is the preferred way over manually adding -framework

**Comment by LeoNero** [comment]
done @selsta

**Review by selsta — APPROVED** [review]

**Pull request merged**
